---
name: Zbuduj projekt

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Build DumpApi App
        run: dotnet build --configuration Release
        working-directory: DumpApi

      - name: Build Docker image
        run: docker build -t dumpapi:latest .

      - name: Show images
        run: docker images

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dumbapi
          path: DumpApi/bin/Release/net8.0
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: damian2z/dumpapi
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          tags: latest